[workspace]
resolver = "2"
members = ["net-guardia", "common", "macros", "ingress-ebpf", "egress-ebpf"]
default-members = ["net-guardia", "common"]

[workspace.dependencies]
aya = { version = "0.13.1", default-features = false }
aya-ebpf = { version = "0.1.1", default-features = false }
aya-log = { version = "0.2.1", default-features = false }
aya-log-ebpf = { version = "0.1.1", default-features = false }
cargo_metadata = { version = "0.22.0", default-features = false }
libc = { version = "0.2.159", default-features = false }
network-types = "0.1.0"
serde = { version = "1.0.215", features = ["derive"] }
xsk-rs = { version = "0.4.1", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
#opt-level = 3
#lto = true
#strip = true
#debug = false
#overflow-checks = false

[profile.release.package.ingress-ebpf]
debug = 2
codegen-units = 1

[profile.release.package.egress-ebpf]
debug = 2
codegen-units = 1
