FROM rockylinux:10

RUN dnf install -y epel-release && \
    crb enable && \
    dnf install -y --allowerasing \
    clang llvm \
    bpftool \
    iproute iproute-tc \
    elfutils-libelf-devel \
    zlib-devel \
    libbpf-devel \
    kernel-headers \
    tcpdump \
    net-tools \
    iputils \
    curl wget \
    git \
    gh \
    vim \
    openssh-server \
    ethtool \
    nodejs24 \
    nodejs24-npm \
    m4 \
    make pkg-config \
    && dnf clean all

# Rust toolchain
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && /root/.cargo/bin/rustup toolchain install nightly \
    && /root/.cargo/bin/rustup component add rust-src --toolchain nightly
ENV PATH="/root/.cargo/bin:${PATH}"

# bpf-linker for aya eBPF compilation
RUN cargo install bpf-linker

RUN ln -s /usr/bin/node-24 /usr/local/bin/node && \
    ln -s /usr/bin/npm-24 /usr/local/bin/npm && \
    ln -s /usr/bin/npx-24 /usr/local/bin/npx

RUN echo 'root:REDACTED' | chpasswd && \
    sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

WORKDIR /root/NetGuardia
CMD sh -c "ssh-keygen -A && /usr/sbin/sshd && sleep infinity"
