[package]
name = "ingress-ebpf"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", features = ["kernel"] }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
network-types = { workspace = true }

[build-dependencies]
which = "8.0.0"

[[bin]]
name = "net-guardia-ingress"
path = "src/main.rs"
