[package]
name = "egress-ebpf"
version = "1.0.0"
edition = "2024"

[dependencies]
net-guardia-abi = { workspace = true, features = ["kernel"] }
aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "net-guardia-egress"
path = "src/main.rs"
test = false
doctest = false
bench = false
