[package]
name = "net-guardia"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", features = ["user"] }
macros = { path = "../macros" }

actix = "0.13.5"
actix-cors = "0.7.1"
actix-web = "4.11.0"
actix-ws = "0.3.0"
aya = { workspace = true }
aya-log = { workspace = true }
crossbeam = "0.8.4"
futures-util = "0.3.30"
libc = { workspace = true }
mime_guess = "2.0.5"
parking_lot = "0.12.5"
rust-embed = "8.7.2"
serde = { workspace = true }
serde_json = "1.0.143"
sysinfo = "0.37.0"
thiserror = "2.0.3"
tokio = { version = "1.40.0", features = ["full", "macros"] }
toml = "0.9.5"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
xsk-rs = { workspace = true }

[build-dependencies]
cargo_metadata = { workspace = true }
dotenvy = "0.15.7"

[[bin]]
name = "net-guardia"
path = "src/main.rs"
